### ISSUE TITLE
Firefox: German subtitles for pictured items

### ISSUE THREAD

**Issue by mjmatthiesen** [shroudedcode/refined-prime-video#12]
Getting german subtitles/transcription for items.
![image](https://user-images.githubusercontent.com/16603906/99005108-6da83c80-24fd-11eb-8d9d-95fee3bfdb03.png)
While I am German, I don't need or want this.

Only get this when the extension is activated.

**Comment by niklashigi** [comment]
That's very weird, I don't see why the extension would trigger this. Can you fix this issue by manually disabling subtitles in the subtitle settings (speech bubble icon in the top right) or do they always return?

**Comment by mjmatthiesen** [comment]
I don't have subtitles enabled at all, which is what makes this even more bizarre to me. What's even more bizarre is that it doesn't happen consistently. I saw it earlier when tracey had a "4th best father cup", but when I reply it, it doesn't happen each time.

**Comment by niklashigi** [comment]
I seriously have no idea why Refined Prime Video would be causing this issue as it doesn't have any features relating to subtitles and doesn't include any code referencing German language codes.

My only theory is that the auto-play URL somehow causes problems.

You could test this by seeing in which of these scenarios the issue occurs:

- Extension **enabled** and auto-play URL from **extension menu** used
- Extension **enabled** and regular URL from **Prime Video homepage/search** used
- Extension **disabled** and auto-play URL from **extension menu** used
- Extension **disabled** and regular URL from **Prime Video homepage/search** used

Please also post both of those URLs here, maybe there are some other unexpected differences between them.

**Comment by mjmatthiesen** [comment]
I'm just going to close this because I cannot reliably reproduce it. Only happened when the extension was installed, but seemingly only the first time the episode ran, and might just be prime weirdness too. It's a really bad and awful website.

Like now it's in Spanish... No one can explain this.
