### ISSUE TITLE
There was a post about adding the ability to hide movies or seasons of shows.

### ISSUE THREAD

**Issue by Tanquen** [shroudedcode/refined-prime-video#13]
I see the options in the LG Smart TV app but they don't work. The movie or show is only removed for a moment or until the next time you come back into the app. I really wish this feature was available on all the platforms. It's a total nightmare slogging through all the shows you've already seen or don't want to see being recommended to you over and over again and in multiple sections I don't know how or why people put up with, it drives me nuts.

**Comment by niklashigi** [comment]
I'm not sure if I quite understand your issue. What does a feature missing in the Prime Video smart TV app have to do with my browser extension for Chrome and Firefox? 🤔

**Comment by Tanquen** [comment]
Mostly just venting but it was said that it had been added to prime so it did not need to be added to the extension. So you're saying if you use the web version of Prime in a Chrome browser the feature will be there and it will work and that's why you don't need to add it to the extension? The feature is there in the TV app but it doesn't work.

**Comment by niklashigi** [comment]
> So you're saying if you use the web version of Prime in a Chrome browser the feature will be there and it will work and that's why you don't need to add it to the extension?

Yes.

**Comment by Tanquen** [comment]
I tried it on the Prime Web app and it seems to work at first but them the hidden movies came back. Oh well. I wish someone would make an app to keep track of all shows on all services and you can hide whatever you wanted and not have to see it in a list or recommendation ever again.
